import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { Display } from "./display";
import { NumberPad } from "./numberPad";

export default function Home() {
  const [displayValue, setDisplayValue] = useState("");
  return (
    <div className={styles.container}>
      <Head>
        <title>Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Display value={displayValue} />
        <NumberPad setDisplayValue={setDisplayValue} />
      </main>
    </div>
  );
}
