import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Display } from "./display";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Display value={123} />
      </main>
    </div>
  );
}
